server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://${DBHOST_ENV:localhost}:3306/productdbkub
    username: root
    password: TempDump989
    driverClassName: com.mysql.cj.jdbc.Driver
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: Product-Service
  config:
     import: configserver:${CONFIG_SERVER_ENV:http://localhost:9296}

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
#  instance:
#    prefer-ip-address: true
